### PR TITLE
TLS InsecureSkipVerify option

### PR DESCRIPTION
**Pull request by vladimirdulov**
@umputun @paskal Please review if you are OK with `go.mod` changes. perhaps a new release of `email` lib is required.

Also could you advise how to update `email` and `auth` libs properly in remark42 app, is it just a copy over?

### CODE REVIEW

**Review by paskal — APPROVED** [review]

**Comment by vladimirdulov** [comment]
The code has been updated in accordance to @paskal comments.

**Comment by vladimirdulov** [comment]
@paskal just submitted `go.sum`, can we try to run CI again?

**Comment by vladimirdulov** [comment]
Could you merge it so I can continue TLS InsecureSkipVerify option implementaton in remark42 app?

Also please advise how to properly get `auth` and `emails` libs updated in the remark42 repo.

**Comment by umputun** [comment]
LGTM, thx

**Pull request merged**
