### PR TITLE
Rename github.com/nullrocks/identicon to github.com/rrivera/identicon

### PR DESCRIPTION
**Pull request by avbasov**
Seems like the author decided to change the username. No changes to the logic of the library. 
https://github.com/rrivera/identicon/commit/2e77a2ee4be00405e88f5cf1d9d3edd07d28d2cb

### CODE REVIEW

**Comment by avbasov** [comment]
Oh, I overlooked that the library now requires go 1.21.5. Not sure what to do with it now.

**Comment by avbasov** [comment]
Well. With go 1.20 in CI it won't pass anyway. May I change the build workflow?

**Comment by umputun** [comment]
Feel free to bump the compiler to 1.21 and adjust the workflow accordingly

**Comment by avbasov** [comment]
Sorry for the mess.

**Comment by umputun** [comment]
thx

**Pull request merged**
