### PR TITLE
Example frontend

### PR DESCRIPTION
**Pull request by Reeywhaar**
Made simple page: [screenshot](https://user-images.githubusercontent.com/884649/50537476-21ee8300-0b71-11e9-83f2-ea40f8c24688.png)

I decided to show private_page as just an iframe, so it doesn't duplicate user info.

I have already [said](https://github.com/go-pkgz/auth/issues/1#issuecomment-450482781) that we have trouble with `token/auth` naming issue. Made an issue #4 

Opened issue #2

Also, I decided not to store `XSRF-TOKEN` cookie anywhere, I think it has no point for example, what do you think?

### CODE REVIEW

**Comment by Reeywhaar** [comment]
About XSRF-TOKEN: I meant that I don't save this cookie value neither in localStorage, nor making it a non-session cookie, so basically, when user close/open browser the XSRF-TOKEN cookie will be missing, but JWT present. Yes right now it has no effect, but I don't know what behaviour would be if xsrf-protection will be on. But, yes, I send it back via headers, as you mentioned:
https://github.com/Reeywhaar/auth/blob/d91d5a77689e6c2cec142be8f51862bf772ae02e/_example/frontend/main.js#L10-L23

About duplication: I meant that I decided to show this page as just an Iframe, and not making it like a table, like I do with `/auth/user` data:
screen shot 2018-12-30 at 01 42 02
Not duplication, but UI similarity and fact that both `/auth/user` and `/private_data` basically contain same data.

**Comment by Reeywhaar** [comment]
How it should be re-obtained when missing? I don't understand what state will be when user make a call to `/auth/user` without XSRF-TOKEN but with JWT? Will it be set with response automatically, or should I make additional request to set this cookie?

**Comment by umputun** [comment]
those cookies should be always paired and both of them set by the server during the login, at the same time. Lack of  XSRF-TOKEN will cause reject after I remove `DisableXSRF:true` flag. Nothing special should be done to re-obtained, just the usual login.

**Comment by Reeywhaar** [comment]
Yeah, my point was to store XSRF-TOKEN in localStorage, to keep sessions between browser reloads. Am I understand right that it expected behaviour to login each time user reloads browser?

**Comment by umputun** [comment]
No, this is not the expected behavior. By default, both cookies are not session cookies and if you reopen the browser they should be in. UI can alter this behavior by sending `&session=1` in login's query params. In this case, both cookies will be session-only and should disappear after browser's restart.

pls note - there is a bug in my refresh logic (just noticed) which may ignore session status and make refresehd JWT cookie non-sessional.

**Comment by Reeywhaar** [comment]
Oh, I see, I was confused and thought XSRF-TOKEN is session only unlike JWT.

**Comment by Reeywhaar** [comment]
Added little more commits (sorry for rebase mess), everything seems working fine.

**Comment by umputun** [comment]
Looks good, thx!

**Pull request merged**
