### PR TITLE
fix iframe xsrf header missing

### PR DESCRIPTION
**Pull request by Reeywhaar**
Fix for #8 

Fix a bit hacky, because there is no way to send headers with an iframe. Have to make ajax call, then create object URL from received data and set url of an iframe to said object URL.

### CODE REVIEW

**Comment by umputun** [comment]
I don't even understand why we need iframe here and then have to resolve issues caused by iframe presence. Maybe just get rid of this completely? If it means a little bit duplication of the code (I think this was the reason for iframe) - so be it.

Anyhow, if you think this how things usually done in ui world - fine with me. I just don't want this example to be tricky or clever.

**Comment by Reeywhaar** [comment]
Nah, it's not tricky, nor clever, it just not, hm, real iframe?
Personally I don't think we need iframe neither, it just was your requirement to show somehow `/private_data`, but basically it's the same data we have in `/auth/user` plus timestamp.
So, remove it?

**Comment by umputun** [comment]
/private_date is not the same as /user. I just didn't have a good idea what unique to return, so just added ts to what I had, but the idea was to demonstrate our ability to hit protected URL and get some data back. Not sure why it even matter what the content of the response if we just show json directly.

**Comment by umputun** [comment]
yeah, just show this json somehow. I had it as <pre> with formatted json.

**Comment by Reeywhaar** [comment]
Check it out.
screen shot 2018-12-31 at 12 04 58

By the way, I noticed that if I login with dev provider under name different from `dev_user`, I'm unable to get contents of `/private_data`. It returns 401 unauthorized.

**Comment by umputun** [comment]
this is exactly as it should be :) https://github.com/go-pkgz/auth/blob/master/_example/backend/main.go#L44

just an example of blocking, it allows dev_ users only and marke dev_admin as admin with some extra attributes

**Pull request merged**
